/** 57 Lucide-style icon keys for Spot It symbols (index = symbolId). */
export const SPOT_IT_SYMBOLS = [
  "circle",
  "square",
  "triangle",
  "star",
  "heart",
  "diamond",
  "hexagon",
  "octagon",
  "moon",
  "sun",
  "cloud",
  "zap",
  "flame",
  "droplet",
  "snowflake",
  "leaf",
  "flower",
  "tree",
  "mountain",
  "waves",
  "anchor",
  "compass",
  "map-pin",
  "home",
  "building",
  "car",
  "plane",
  "ship",
  "bike",
  "rocket",
  "key",
  "lock",
  "bell",
  "clock",
  "hourglass",
  "camera",
  "music",
  "mic",
  "headphones",
  "radio",
  "tv",
  "phone",
  "mail",
  "gift",
  "crown",
  "trophy",
  "target",
  "flag",
  "bookmark",
  "scissors",
  "pencil",
  "brush",
  "palette",
  "eye",
  "smile",
  "ghost",
  "cat",
] as const;

export type SpotItSymbolKey = (typeof SPOT_IT_SYMBOLS)[number];

export function symbolKey(id: number): SpotItSymbolKey {
  const n = SPOT_IT_SYMBOLS.length;
  return SPOT_IT_SYMBOLS[((id % n) + n) % n]!;
}
